### ISSUE TITLE
No signal when connecting the DK after starting RSSI Viewer

### ISSUE THREAD

**Issue by SebastianBoe** [NordicSemiconductor/pc-nrfconnect-rssi#23] opened 2018-01-12 13:35 UTC
Hi,

I'm not getting a signal.

Not sure what I could be doing wrong ...

You don't need to have a device advertising to guarantee that some noise will be registered, or?
And there is no GO button that I'm not seeing, or?

> 
> sebo@mach:~/Downloads/nrfconnect-2.2.1$ ./nrfconnect 
> Gtk-Message: Failed to load module "overlay-scrollbar"
> [14:23:50:0059] [warn] Not checking for nRF Connect updates. Auto update is not yet supported for this platform.
> Created new window in existing browser session.
> [11309:11346:0112/142431.909435:ERROR:browser_gpu_channel_host_factory.cc(107)] Failed to launch GPU process.
> 

> 
> 14:26:10.8900	Application data folder: /home/sebo/.config/nrfconnect
> 14:28:04.8600	/dev/ttyACM0 is open

**Comment by IvanSanchez** [comment] 2018-01-12 13:37
@SebastianBoe What kind of devkit are you using? An you're on Linux, right?

**Comment by SebastianBoe** [comment] 2018-01-12 13:39
Hah, rebooted nrfconnect and it worked.

Perhaps it doesn't work if the DK does not already have the FW flashed.

PC10040

Ubuntu 16.04.

**Comment by SebastianBoe** [comment] 2018-01-12 13:40
Logs from first and second boot.

> sebo@mach:~/Downloads/nrfconnect-2.2.1$ ./nrfconnect 
> Gtk-Message: Failed to load module "overlay-scrollbar"
> [14:23:50:0059] [warn] Not checking for nRF Connect updates. Auto update is not yet supported for this platform.
> Created new window in existing browser session.
> [11309:11346:0112/142431.909435:ERROR:browser_gpu_channel_host_factory.cc(107)] Failed to launch GPU process.
> sebo@mach:~/Downloads/nrfconnect-2.2.1$ ./nrfconnect 
> Gtk-Message: Failed to load module "overlay-scrollbar"
> [14:37:37:0888] [warn] Not checking for nRF Connect updates. Auto update is not yet supported for this platform.
>

**Comment by SebastianBoe** [comment] 2018-01-12 13:41
Only differene is the gpu error. Don't know if it's related though.

**Comment by SebastianBoe** [comment] 2018-01-12 13:43
In addition to the signal not showing, the LED button wasn't working on the first boot. Now it is.

**Comment by IvanSanchez** [comment] 2018-01-12 13:46
nrfconnect is supposed to check that the right firmware is already in the devkit, and offer a GUI dialog (puts nothing in the log, though).

You might encounter scenarios where the serial port (`/dev/ttyACM0`) cannot be opened, or is claimed by `ModemManager`, or is lacking permissions.

Is this reproducible? I mean: Does the problem keep happening after unplugging the devkit, closing nrfconnect and starting everything again?

**Comment by SebastianBoe** [comment] 2018-01-12 13:52
> nrfconnect is supposed to check that the right firmware is already in the devkit, and offer a GUI dialog (puts nothing in the log, though).

It did.

> Is this reproducible? I mean: Does the problem keep happening after unplugging the devkit, closing nrfconnect and starting everything again?

Let me try to reproduce ...

**Comment by SebastianBoe** [comment] 2018-01-12 14:16
Yep, was able to reproduce.

When I connect the devkit AFTER booting RSSI Viewer I don't get a signal.
When I connect the devkit BEFORE booting RSSI Viewer I get a signal.

**Comment by SebastianBoe** [comment] 2018-01-12 14:18
@IvanSanchez : This is what I was talking about when discussing udev. Don't know if it is related to any of this though.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jlink-software-and-documentation#n52

**Comment by IvanSanchez** [comment] 2018-01-12 14:25
I can reproduce, kinda.

It seems that there is a noticeable (~2sec) delay between the serial port being opened, and data starting to come. And this delay only shows up whenever *first* launching nrfconnect *then* powering up the devkit. I'm gonna guess you're experiencing a similar problem, or that there is a race condition that's affecting your hardware in a slightly different way.

**Comment by bencefr** [comment] 2018-08-31 06:00
Closing due to inactivity.

**Closed by bencefr** 2018-08-31 06:00 UTC
